### PR TITLE
Fix: Filename

### PR DESCRIPTION
**Pull request by ghost**
@prathimacode-hub mistakely added the config.yml to the workflows folder instead of .github

### CODE REVIEW

**Review by akhileshthite — APPROVED** [review]

**Comment by prathimacode-hub** [comment]
Actually while using Github Actions, we don't create workflows folder separately while adding up a file. It automates the folder and saves the file with our given file name. If done without the Github Actions, it can be saved separately as a file. I had used Actions. Correct me, if i am wrong. It was not by mistake, but since configuration file is part of workflow. I did setup that way. No issues, as long as @AkhileshThite is fine with it. 👍 @krishdevdb

**Comment by akhileshthite** [comment]
> Actually while using Github Actions, we don't create workflows folder separately while adding up a file. It automates the folder and saves the file with our given file name. If done without the Github Actions, it can be saved separately as a file. I had used Actions. Correct me, if i am wrong. It was not by mistake, but since configuration file is part of workflow. I did setup that way. No issues, as long as @AkhileshThite is fine with it. 👍 @krishdevdb

I saved the config.yml settings for this repo through the following link `https://github.com/apps/welcome`, but GitHub actions were giving me `Run failed: .github/workflows/config.yml `

**Comment by prathimacode-hub** [comment]
Ok, my bad then. @AkhileshThite

**Comment by akhileshthite** [comment]
> Ok, my bad then. @AkhileshThite

No worries.

**Comment by ghost** [comment]
But @AkhileshThite the action doesn't seem to be setup yet!

**Pull request merged**
